# Generated by Django 4.2.1 on 2023-05-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_bids_bid_bids_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
