# Generated by Django 4.2.1 on 2023-05-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bids_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
