# Generated by Django 4.2.1 on 2023-05-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_bids_bid_bids_bid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
