# Generated by Django 4.2.1 on 2023-06-12 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_comments_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='watchlist',
            field=models.ManyToManyField(null=True, related_name='mywatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
